# 安定版 Ubuntu LTS
FROM ubuntu:24.04

USER root

# パッケージリスト更新
RUN apt update

# Python関連インストール
RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y python3-venv

# requirements ファイルをコピー
COPY docker_requirements.txt /tmp/docker_requirements.txt

# ライブラリインストール
RUN python3 -m pip install --break-system-packages -r /tmp/docker_requirements.txt
